# Generated by CMake, DO NOT EDIT

empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jamesfolk/Documents/NJLI/Engine/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jamesfolk/Documents/NJLI/Engine/cmake.in/NJLIGameEngineConfig.h.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jamesfolk/Documents/NJLI/Engine/projects/macOS_Xcode/CMakeFiles/3.7.2/CMakeCCompiler.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jamesfolk/Documents/NJLI/Engine/projects/macOS_Xcode/CMakeFiles/3.7.2/CMakeCXXCompiler.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jamesfolk/Documents/NJLI/Engine/projects/macOS_Xcode/CMakeFiles/3.7.2/CMakeSystem.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/CMakeCInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/CMakeCXXInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/CMakeCommonLanguageInclude.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/CMakeGenericSystem.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/CMakeLanguageInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/CMakeSystemSpecificInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/Compiler/AppleClang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/Compiler/AppleClang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/Compiler/Clang.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/Compiler/GNU.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/Platform/Darwin-AppleClang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/Platform/Darwin-AppleClang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/Platform/Darwin-Clang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/Platform/Darwin-Clang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/Platform/Darwin-Clang.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/Platform/Darwin-Initialize.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/Platform/Darwin.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/Platform/UnixPaths.cmake))

/Users/jamesfolk/Documents/NJLI/Engine/projects/macOS_Xcode/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.7.2/bin/cmake -H/Users/jamesfolk/Documents/NJLI/Engine -B/Users/jamesfolk/Documents/NJLI/Engine/projects/macOS_Xcode
