/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class source_android_engine_njligames_com_android_androidstudio_SDLActivity */

#ifndef _Included_source_android_engine_njligames_com_android_androidstudio_SDLActivity
#define _Included_source_android_engine_njligames_com_android_androidstudio_SDLActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_BIND_ABOVE_CLIENT
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_BIND_ABOVE_CLIENT 8L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_BIND_ADJUST_WITH_ACTIVITY
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_BIND_ADJUST_WITH_ACTIVITY 128L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_BIND_ALLOW_OOM_MANAGEMENT
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_BIND_AUTO_CREATE
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_BIND_AUTO_CREATE 1L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_BIND_DEBUG_UNBIND
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_BIND_DEBUG_UNBIND 2L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_BIND_EXTERNAL_SERVICE
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_BIND_EXTERNAL_SERVICE -2147483648L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_BIND_IMPORTANT
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_BIND_IMPORTANT 64L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_BIND_NOT_FOREGROUND
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_BIND_NOT_FOREGROUND 4L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_BIND_WAIVE_PRIORITY
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_BIND_WAIVE_PRIORITY 32L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_CONTEXT_IGNORE_SECURITY
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_CONTEXT_IGNORE_SECURITY 2L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_CONTEXT_INCLUDE_CODE
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_CONTEXT_INCLUDE_CODE 1L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_CONTEXT_RESTRICTED
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_CONTEXT_RESTRICTED 4L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_MODE_APPEND
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_MODE_APPEND 32768L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_MODE_MULTI_PROCESS
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_MODE_MULTI_PROCESS 4L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_MODE_NO_LOCALIZED_COLLATORS
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_MODE_NO_LOCALIZED_COLLATORS 16L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_MODE_PRIVATE
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_MODE_PRIVATE 0L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_MODE_WORLD_READABLE
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_MODE_WORLD_READABLE 1L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_MODE_WORLD_WRITEABLE
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_MODE_WORLD_WRITEABLE 2L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_DEFAULT_KEYS_DIALER
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_DEFAULT_KEYS_DIALER 1L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_DEFAULT_KEYS_DISABLE
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_DEFAULT_KEYS_DISABLE 0L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_DEFAULT_KEYS_SEARCH_GLOBAL
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_DEFAULT_KEYS_SEARCH_GLOBAL 4L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_DEFAULT_KEYS_SEARCH_LOCAL
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_DEFAULT_KEYS_SHORTCUT
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_DEFAULT_KEYS_SHORTCUT 2L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_RESULT_CANCELED
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_RESULT_CANCELED 0L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_RESULT_FIRST_USER
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_RESULT_FIRST_USER 1L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_RESULT_OK
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_RESULT_OK -1L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_COMMAND_CHANGE_TITLE
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_COMMAND_CHANGE_TITLE 1L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_COMMAND_UNUSED
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_COMMAND_UNUSED 2L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_COMMAND_TEXTEDIT_HIDE
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_COMMAND_TEXTEDIT_HIDE 3L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_COMMAND_SET_KEEP_SCREEN_ON
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_COMMAND_SET_KEEP_SCREEN_ON 5L
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_COMMAND_USER
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_COMMAND_USER 32768L
/*
 * Class:     source_android_engine_njligames_com_android_androidstudio_SDLActivity
 * Method:    nativeInit
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_source_android_engine_njligames_com_android_1androidstudio_SDLActivity_nativeInit
  (JNIEnv *, jclass, jobject);

/*
 * Class:     source_android_engine_njligames_com_android_androidstudio_SDLActivity
 * Method:    nativeLowMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_source_android_engine_njligames_com_android_1androidstudio_SDLActivity_nativeLowMemory
  (JNIEnv *, jclass);

/*
 * Class:     source_android_engine_njligames_com_android_androidstudio_SDLActivity
 * Method:    nativeQuit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_source_android_engine_njligames_com_android_1androidstudio_SDLActivity_nativeQuit
  (JNIEnv *, jclass);

/*
 * Class:     source_android_engine_njligames_com_android_androidstudio_SDLActivity
 * Method:    nativePause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_source_android_engine_njligames_com_android_1androidstudio_SDLActivity_nativePause
  (JNIEnv *, jclass);

/*
 * Class:     source_android_engine_njligames_com_android_androidstudio_SDLActivity
 * Method:    nativeResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_source_android_engine_njligames_com_android_1androidstudio_SDLActivity_nativeResume
  (JNIEnv *, jclass);

/*
 * Class:     source_android_engine_njligames_com_android_androidstudio_SDLActivity
 * Method:    onNativeDropFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_source_android_engine_njligames_com_android_1androidstudio_SDLActivity_onNativeDropFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     source_android_engine_njligames_com_android_androidstudio_SDLActivity
 * Method:    onNativeResize
 * Signature: (IIIF)V
 */
JNIEXPORT void JNICALL Java_source_android_engine_njligames_com_android_1androidstudio_SDLActivity_onNativeResize
  (JNIEnv *, jclass, jint, jint, jint, jfloat);

/*
 * Class:     source_android_engine_njligames_com_android_androidstudio_SDLActivity
 * Method:    onNativePadDown
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_source_android_engine_njligames_com_android_1androidstudio_SDLActivity_onNativePadDown
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     source_android_engine_njligames_com_android_androidstudio_SDLActivity
 * Method:    onNativePadUp
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_source_android_engine_njligames_com_android_1androidstudio_SDLActivity_onNativePadUp
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     source_android_engine_njligames_com_android_androidstudio_SDLActivity
 * Method:    onNativeJoy
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_source_android_engine_njligames_com_android_1androidstudio_SDLActivity_onNativeJoy
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     source_android_engine_njligames_com_android_androidstudio_SDLActivity
 * Method:    onNativeHat
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_source_android_engine_njligames_com_android_1androidstudio_SDLActivity_onNativeHat
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     source_android_engine_njligames_com_android_androidstudio_SDLActivity
 * Method:    onNativeKeyDown
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_source_android_engine_njligames_com_android_1androidstudio_SDLActivity_onNativeKeyDown
  (JNIEnv *, jclass, jint);

/*
 * Class:     source_android_engine_njligames_com_android_androidstudio_SDLActivity
 * Method:    onNativeKeyUp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_source_android_engine_njligames_com_android_1androidstudio_SDLActivity_onNativeKeyUp
  (JNIEnv *, jclass, jint);

/*
 * Class:     source_android_engine_njligames_com_android_androidstudio_SDLActivity
 * Method:    onNativeKeyboardFocusLost
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_source_android_engine_njligames_com_android_1androidstudio_SDLActivity_onNativeKeyboardFocusLost
  (JNIEnv *, jclass);

/*
 * Class:     source_android_engine_njligames_com_android_androidstudio_SDLActivity
 * Method:    onNativeMouse
 * Signature: (IIFF)V
 */
JNIEXPORT void JNICALL Java_source_android_engine_njligames_com_android_1androidstudio_SDLActivity_onNativeMouse
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat);

/*
 * Class:     source_android_engine_njligames_com_android_androidstudio_SDLActivity
 * Method:    onNativeTouch
 * Signature: (IIIFFF)V
 */
JNIEXPORT void JNICALL Java_source_android_engine_njligames_com_android_1androidstudio_SDLActivity_onNativeTouch
  (JNIEnv *, jclass, jint, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     source_android_engine_njligames_com_android_androidstudio_SDLActivity
 * Method:    onNativeAccel
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_source_android_engine_njligames_com_android_1androidstudio_SDLActivity_onNativeAccel
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     source_android_engine_njligames_com_android_androidstudio_SDLActivity
 * Method:    onNativeSurfaceChanged
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_source_android_engine_njligames_com_android_1androidstudio_SDLActivity_onNativeSurfaceChanged
  (JNIEnv *, jclass);

/*
 * Class:     source_android_engine_njligames_com_android_androidstudio_SDLActivity
 * Method:    onNativeSurfaceDestroyed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_source_android_engine_njligames_com_android_1androidstudio_SDLActivity_onNativeSurfaceDestroyed
  (JNIEnv *, jclass);

/*
 * Class:     source_android_engine_njligames_com_android_androidstudio_SDLActivity
 * Method:    nativeAddJoystick
 * Signature: (ILjava/lang/String;IIIII)I
 */
JNIEXPORT jint JNICALL Java_source_android_engine_njligames_com_android_1androidstudio_SDLActivity_nativeAddJoystick
  (JNIEnv *, jclass, jint, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     source_android_engine_njligames_com_android_androidstudio_SDLActivity
 * Method:    nativeRemoveJoystick
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_source_android_engine_njligames_com_android_1androidstudio_SDLActivity_nativeRemoveJoystick
  (JNIEnv *, jclass, jint);

/*
 * Class:     source_android_engine_njligames_com_android_androidstudio_SDLActivity
 * Method:    nativeGetHint
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_source_android_engine_njligames_com_android_1androidstudio_SDLActivity_nativeGetHint
  (JNIEnv *, jclass, jstring);

/*
 * Class:     source_android_engine_njligames_com_android_androidstudio_SDLActivity
 * Method:    initAssetManager
 * Signature: (Landroid/content/res/AssetManager;)V
 */
JNIEXPORT void JNICALL Java_source_android_engine_njligames_com_android_1androidstudio_SDLActivity_initAssetManager
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class source_android_engine_njligames_com_android_androidstudio_SDLActivity_ShowTextInputTask */

#ifndef _Included_source_android_engine_njligames_com_android_androidstudio_SDLActivity_ShowTextInputTask
#define _Included_source_android_engine_njligames_com_android_androidstudio_SDLActivity_ShowTextInputTask
#ifdef __cplusplus
extern "C" {
#endif
#undef source_android_engine_njligames_com_android_androidstudio_SDLActivity_ShowTextInputTask_HEIGHT_PADDING
#define source_android_engine_njligames_com_android_androidstudio_SDLActivity_ShowTextInputTask_HEIGHT_PADDING 15L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class source_android_engine_njligames_com_android_androidstudio_SDLActivity_SDLCommandHandler */

#ifndef _Included_source_android_engine_njligames_com_android_androidstudio_SDLActivity_SDLCommandHandler
#define _Included_source_android_engine_njligames_com_android_androidstudio_SDLActivity_SDLCommandHandler
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
